name: Build Documentation

on:
  push:
    branches:
      - main

jobs:
  build-documentation:
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: read
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Print NPM version 🌎
        run: npm --version

      - name: Install the dependencies 🧱
        run: npm ci

      - name: Build the documentation 🔨
        run: npm run docs

      - name: Setup GitHub Pages 🛠
        uses: actions/configure-pages@v6

      - name: Upload artifact ⬆️
        uses: actions/upload-pages-artifact@v5
        with:
          path: docs

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v5
