name: Publish Package

on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Print NPM version 🌎
        run: npm --version

      - name: Install the dependencies 🔧
        run: npm ci

      - name: Build the package 🔧
        run: npm run build

      - name: Configure NPMJS 🔧
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'

      - name: Deploy to NPMJS 🚀
        run: npm publish
